import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export type StreamingReport = {
  period: string;
  activeViewers: number;
  playbackHours: number;
  completionRate: number;
  topTitle: string;
};

export async function renderStreamingReport(report: StreamingReport): Promise<Uint8Array> {
  const document = await PDFDocument.create();
  const page = document.addPage([612, 792]);
  const regular = await document.embedFont(StandardFonts.Helvetica);
  const bold = await document.embedFont(StandardFonts.HelveticaBold);

  page.drawText("Streaming audience report", { x: 54, y: 720, size: 24, font: bold, color: rgb(0.08, 0.16, 0.25) });
  page.drawText(report.period, { x: 54, y: 690, size: 11, font: regular, color: rgb(0.35, 0.4, 0.45) });

  const rows = [
    ["Active viewers", report.activeViewers.toLocaleString("en-US")],
    ["Playback hours", report.playbackHours.toLocaleString("en-US")],
    ["Completion rate", `${(report.completionRate * 100).toFixed(1)}%`],
    ["Top title", report.topTitle],
  ];
  rows.forEach(([label, value], index) => {
    const y = 625 - index * 58;
    page.drawText(label ?? "", { x: 54, y, size: 11, font: regular, color: rgb(0.35, 0.4, 0.45) });
    page.drawText(value ?? "", { x: 220, y, size: 14, font: bold, color: rgb(0.08, 0.16, 0.25) });
  });

  page.drawText("Generated by the audience reporting job", { x: 54, y: 72, size: 9, font: regular, color: rgb(0.45, 0.5, 0.55) });
  return document.save();
}
